version: '3.8'
services:
  ctp-metrics:
    container_name: ctp-metrics
    image: ctp-metrics:latest
    environment:
      BASE_URL_CTP: "http://192.168.1.83:8080" # IPLOCAL
      MONGODB_HOST: "192.168.1.83"
      MONGODB_PORT: "3307"
      MONGODB_USER: "admin"
      MONGODB_PASS: "admin"
      CRONJOB: "false"
    ports:
      - "5000:5000"
